# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_expiredatetokenspotify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='current_user',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to='api.User'),
        ),
    ]
