# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160101_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='android_tag',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
