# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_track_android_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='android_tag',
        ),
    ]
