# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_party_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artist_name',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
