# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_track_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(max_length=255),
        ),
    ]
