# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160104_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='played_time',
            field=models.IntegerField(null=True),
        ),
    ]
